id = "rasmus-theme"
name = "Rasmus Theme"
version = "0.5.0"
schema_version = 1
authors = ["blaqat <blaqat.ag@gmail.com>"]
description = "Rasmus theme for Zed"
repository = "https://github.com/biaqat/rasmus-theme-zed"
